# Generated by Django 3.2.9 on 2021-11-15 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Present_Address', models.TextField(blank=True, max_length=255, null=True)),
                ('Permanant_Address', models.TextField(blank=True, max_length=255, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='User_image')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
