# Generated by Django 3.2.9 on 2021-11-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_userprofilem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilem',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
