# Generated by Django 3.2.9 on 2021-11-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_userprofilem_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilem',
            name='Email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
