# Generated by Django 3.2.9 on 2021-11-19 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0008_alter_userprofilem_branch_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_box', models.CharField(blank=True, max_length=1000, null=True)),
                ('mrno', models.CharField(blank=True, max_length=50, null=True)),
                ('dates', models.DateField(auto_now=True)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
