# Generated by Django 3.2.9 on 2021-11-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.userprofilem'),
        ),
    ]
