# Generated by Django 3.2.9 on 2021-11-19 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0010_chat_branch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat',
            new_name='chatV',
        ),
    ]
