# Generated by Django 3.2.9 on 2021-11-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_rename_chatv_chatm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatm',
            name='branch',
        ),
    ]
