# Generated by Django 3.2.9 on 2021-11-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_alter_chatm_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatm',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
